# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
name: Slack notifications
description: Slack notifications for deployments

inputs:
    app_name:
      description: Name of tenant app_name to deploy to, e.g. testapp1
      required: true
      type: string
    env_name:
      description: Name of tenant env to deploy to, e.g. dev
      required: true
      type: string
    type:
      description: Message type to be sent, supported values 'start', 'end', 'failed', 'custom'
      required: true
      type: string
    channel_id:
      description: Slack channel id to send messages
      required: true
      type: string
    slack_bot_token:
      description: Slack bot token oauth secret
      required: true
      type: string
    ref:
      description: Deployment ref
      required: false
      type: string
    message:
      description: Custom message when inputs.type is set to 'custom'
      required: false
      type: string
      default: ""
    color:
      description: Custom color when inputs.type is set to 'custom'
      required: false
      type: string
      default: "#28a745"
    mentions:
      description: Slack users or groups to mention in the message
      required: false
      type: string
      default: ""
    update_ts:
      description: Message ts for updating sent messages
      required: false
      type: string
outputs:
  ts:
    description: Slack ts for updating messages
    value: ${{ steps.slack.outputs.ts }}

runs:
  using: composite
  steps:
    - id: slack
      uses: slackapi/slack-github-action@v1.25.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
        MESSAGE: >-
          {
            "start": {
              "attachments": [
                {
                  "color": "#dbab09",
                  "fallback": "${{ inputs.app_name }} ${{ inputs.env_name }}: start",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.app_name }} ${{ inputs.env_name }}: Deploy started - ${{ inputs.ref }} ${{ inputs.mentions }}"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Github Actions",
                          "emoji": true
                        },
                        "value": "click",
                        "url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
                        "action_id": "button-action"
                      }
                    }
                  ]
                }
              ]
            },
            "end": {
              "attachments": [
                {
                  "color": "#28a745",
                  "fallback": "${{ inputs.app_name }} ${{ inputs.env_name }}: end",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.app_name }} ${{ inputs.env_name }}: Deploy complete - ${{ inputs.ref }} ${{ inputs.mentions }}"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Github Actions",
                          "emoji": true
                        },
                        "value": "click",
                        "url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
                        "action_id": "button-action"
                      }
                    }
                  ]
                }
              ]
            },
            "failed": {
              "attachments": [
                {
                  "color": "#a72841",
                  "fallback": "${{ inputs.app_name }} ${{ inputs.env_name }}: failed",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.app_name }} ${{ inputs.env_name }}: Deploy failed - ${{ inputs.ref }} ${{ inputs.mentions }}"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Github Actions",
                          "emoji": true
                        },
                        "value": "click",
                        "url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
                        "action_id": "button-action"
                      }
                    }
                  ]
                }
              ]
            },
            "custom": {
              "attachments": [
                {
                  "color": "${{ inputs.color }}",
                  "fallback": "${{ inputs.app_name }} ${{ inputs.env_name }}: custom",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.app_name }} ${{ inputs.env_name }}: ${{ inputs.message }}"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Github Actions",
                          "emoji": true
                        },
                        "value": "click",
                        "url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
                        "action_id": "button-action"
                      }
                    }
                  ]
                }
              ]
            }
          }
      with:
        channel-id: ${{ inputs.channel_id }}
        payload: ${{ toJSON(fromJson(env.MESSAGE)[inputs.type]) }}
        update-ts: ${{ inputs.update_ts }}
