name: docker-build
description: |
  This GitHub Action is designed to build a Docker container image, providing
  standard MozCloud tags for supported registries. It loads the built image
  into the local Docker context, making it available for immediate use in
  subsequent workflow steps (e.g., in docker compose files).

  The action outputs a list of registry images in image_tags to be consumed by
  the docker-push action. In addition to the GAR and optionally GHCR image,
  the action also tags the built image with the plain `image_name` input for
  local use only. This local tag is not included in the action's outputs and
  will not be pushed to any registry.
inputs:
  image_name:
    description: Name to give to the built image
    required: true
  gar_location:
    description: GCP region where GAR is located
    required: false
    default: us
  gar_name:
    description: Name of the GAR repository
    required: true
  project_id:
    description: GCP project ID
    required: true
  docker_build_args:
    default: ""
    description: Build-time variables
    required: false
  image_build_context:
    description: Path to the Docker build context
    required: false
    default: ./
  dockerfile_path:
    description: Path to the Dockerfile
    required: false
    default: ./Dockerfile
  image_tag_metadata:
    description: Metadata to append to image tag
    required: false
  should_tag_ghcr:
    description: Tag images for GitHub Container Registry
    required: false
    default: "false"
  should_tag_latest:
    description: Tag images as latest
    required: false
    default: "false"
  enable_attestations:
    description: Enable SBOM and provenance attestations for supply chain security
    required: false
    default: "false"

outputs:
  image_tags:
    description: "A newline-delimited list of generated Docker image tags"
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: composite
  steps:
    - name: Set up Docker
      if: ${{ inputs.enable_attestations == 'true' }}
      uses: docker/setup-docker-action@v4
      with:
        daemon-config: |
          {
            "features": {
              "containerd-snapshotter": true
            }
          }
    - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #v3.12.0
    - name: Generate MozCloud Tag
      id: mozcloud-tag
      shell: bash
      env:
        REF_TYPE: ${{ github.ref_type }}
        REF_NAME: ${{ github.ref_name }}
        IMAGE_TAG_METADATA: ${{ inputs.image_tag_metadata }}
      run: |
        if [[ "${REF_TYPE}" == "tag" ]]; then
          tag="${REF_NAME}"
        else
          tag="$(git rev-parse --short=10 HEAD)"
        fi
        # append metadata if present
        if [[ -n "${IMAGE_TAG_METADATA}" ]]; then
          tag="${tag}--${IMAGE_TAG_METADATA}"
        fi
        echo "Setting IMAGE_TAG=${tag} as output"
        echo "image_tag=${tag}" >> "$GITHUB_OUTPUT"

    - name: Set image list
      shell: bash
      id: set-images
      env:
        GAR_LOCATION: ${{ inputs.gar_location }}
        PROJECT_ID: ${{ inputs.project_id }}
        GAR_NAME: ${{ inputs.gar_name }}
        IMAGE_NAME: ${{ inputs.image_name }}
        SHOULD_TAG_GHCR: ${{ inputs.should_tag_ghcr }}
      run: |
        images=( "${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_NAME}/${IMAGE_NAME}" )
        if [[ "${SHOULD_TAG_GHCR}" == "true" ]]; then
          images+=( "ghcr.io/${{ github.repository }}/${IMAGE_NAME}" )
        fi

        # Debug output
        echo "Generated Images:"
        printf '%s\n' "${images[@]}"

        {
          echo "images<<EOF"
          printf '%s\n' "${images[@]}"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Set tag list
      shell: bash
      id: set-tags
      env:
        SHOULD_TAG_LATEST: ${{ inputs.should_tag_latest }}
        IMAGE_TAG: ${{ steps.mozcloud-tag.outputs.image_tag }}
      run: |
        tags=( "type=raw,value=${IMAGE_TAG}" )
        if [[ "${SHOULD_TAG_LATEST}" == "true" ]]; then
          tags+=( "type=raw,value=latest" )
        fi

        # Debug output
        echo "Generated Tags:"
        printf '%s\n' "${tags[@]}"

        {
          echo "tags<<EOF"
          printf '%s\n' "${tags[@]}"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 #v5.7.0
      with:
        images: ${{ steps.set-images.outputs.images }}
        tags: ${{ steps.set-tags.outputs.tags }}
    # https://docs.docker.com/build/ci/github-actions/checks/#run-checks-with-dockerbuild-push-action
    - name: Check image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
      with:
        call: check
        # We can't use the intermediate env var trick to appease zizmor in this
        # case. We'll have to rely on docker/build-push-action to handle
        # santizing this input
        context: ${{ inputs.image_build_context }} # zizmor: ignore[template-injection]
        build-args: ${{ inputs.docker_build_args }}
        file: ${{ inputs.dockerfile_path }}
    - name: Build image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
      with:
        # We can't use the intermediate env var trick to appease zizmor in this
        # case. We'll have to rely on docker/build-push-action to handle
        # santizing this input
        context: ${{ inputs.image_build_context }} # zizmor: ignore[template-injection]
        build-args: ${{ inputs.docker_build_args }}
        file: ${{ inputs.dockerfile_path }}
        # in addition to tags generated by docker-metadata, add the plain
        # `${{ inputs.image_name }}` so that it can be referred to by that
        # more familiar name in scripts
        tags: |
          ${{ inputs.image_name }}
          ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        push: false
        load: true
        sbom: ${{ inputs.enable_attestations == 'true' }}
        provenance: ${{ inputs.enable_attestations == 'true' && 'mode=max' || 'false' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
