name: docker-push
description: |
  This GitHub Action is designed to push Docker images to Google Artifact
  Registry (GAR) and optionally GitHub Container Registry (GHCR).

inputs:
  image_tags:
    description: Newline-delimited list of images to be pushed
    required: true
  workload_identity_pool_project_number:
    description: Project number of workload identity pool used for OIDC authentication
    required: true
  project_id:
    description: GCP project_id used to construct the service account
    required: true
  gar_location:
    description: GCP region where target GAR is located
    required: false
    default: "us"
  should_authenticate_to_ghcr:
    description: Whether or not to authenticate to Github Container Registry
    required: false
    default: "false"
  service_account_name:
    description: Service account used to authenticate to GAR
    default: artifact-writer

runs:
  using: composite
  steps:
    - name: Authenticate to GCP
      id: gcp_auth
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 #v3
      with:
        workload_identity_provider: "projects/${{ inputs.workload_identity_pool_project_number }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
        service_account: "${{ inputs.service_account_name }}@${{ inputs.project_id }}.iam.gserviceaccount.com"
        token_format: access_token
        create_credentials_file: false
    - name: Log in to GAR
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 #v3.7.0
      with:
        registry: ${{ inputs.gar_location }}-docker.pkg.dev
        username: oauth2accesstoken
        password: "${{ steps.gcp_auth.outputs.access_token }}"
    - name: Log in to GitHub Container Registry
      if: inputs.should_authenticate_to_ghcr == 'true'
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Push Docker image(s)
      shell: bash
      env:
        IMAGE_TAGS: ${{ inputs.image_tags }}
      run: |
        while IFS= read -r image_tag; do
            docker push $image_tag 
        done <<< "${IMAGE_TAGS}"
