# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Reusable workflow to render and diff helm charts between the head and base ref of a pull request
# A comment is made on the pull request containing the diff output

name: render and diff helm charts
on:
  workflow_call:

jobs:
  get_changed_helm_charts:
    runs-on: ubuntu-latest
    outputs:
      matrix_charts: ${{ steps.find_changed_charts.outputs.matrix_changed_charts }}
      charts: ${{ steps.find_changed_charts.outputs.changed_charts }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
         fetch-depth: '100'
         persist-credentials: true # We are using these credentials in later steps

      - name: find changed helm charts
        id: find_changed_charts
        run: |
          git fetch origin ${GITHUB_BASE_REF}:${GITHUB_BASE_REF}
          echo matrix_changed_charts=$(git diff --name-only ${GITHUB_BASE_REF}...HEAD -- '**/k8s/**/*.yaml' '**/k8s/**/*.yml' '**/k8s/**/*.tpl' '**/k8s/**/*.tmpl' | cut -d'/' -f1,2,3 | uniq | jq -R 'split("\n")' | jq -s 'flatten(1)') >> $GITHUB_OUTPUT
          echo changed_charts=$(git diff --name-only ${GITHUB_BASE_REF}...HEAD -- '**/k8s/**/*.yaml' '**/k8s/**/*.yml' '**/k8s/**/*.tpl' '**/k8s/**/*.tmpl' | cut -d'/' -f1,2,3 | uniq) >> $GITHUB_OUTPUT
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}

  render_charts:
    runs-on: ubuntu-latest
    needs: get_changed_helm_charts
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.get_changed_helm_charts.outputs.matrix_charts) }}
        ref: 
          - name: base
            sha: ${{ github.base_ref }}
          - name: head
            sha: ${{ github.head_ref }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true # We are using these credentials in later steps
          ref: ${{ matrix.ref.sha }}

      - name: setup helm
        uses: azure/setup-helm@29960d0f5f19214b88e1d9ba750a9914ab0f1a2f #v4.0.0

      - name: render ${{ matrix.chart }} from ${{ matrix.ref.name }} ref
        id: render
        run: |
          mkdir -p shared/${MATRIX_REF_NAME}-charts
          if [ -f "${MATRIX_CHART}/Chart.yaml" ]; then
            helm dependency update "${MATRIX_CHART}"
            values_files=$(find "$MATRIX_CHART" -maxdepth 1 -type f \( -name '*values*.yaml' -o -name '*values*.yml' \) ! \( -name 'values.yaml' -o -name 'values.yml' \))

            for values_path in ${values_files}; do
              values_file=$(basename "$values_path")
              env=$(echo "$values_file" | sed -E 's/^values-([a-z0-9]+)(-.+)?\.yaml$/\1/')
              region=$(echo "$values_file" | sed -nE "s/^values-${env}-(.+)\.yaml$/\1/p")

              output_name=$(basename "$values_file" .yaml)
              render_path="shared/${MATRIX_REF_NAME}-charts/${MATRIX_CHART}/${output_name}"
              mkdir -p "$render_path"

              if [[ -n "$region" && -f "${MATRIX_CHART}/values-${env}.yaml" ]]; then
                # Render with three layers: base, env, env-region
                helm template "${MATRIX_CHART}" \
                  -f "${MATRIX_CHART}/values.yaml" \
                  -f "${MATRIX_CHART}/values-${env}.yaml" \
                  -f "${MATRIX_CHART}/${values_file}" \
                  --output-dir "$render_path"
              else
                # Only base + environment file
                helm template "${MATRIX_CHART}" \
                  -f "${MATRIX_CHART}/values.yaml" \
                  -f "${MATRIX_CHART}/${values_file}" \
                  --output-dir "$render_path"
              fi
           done
          fi
          echo sanitized_name=$(echo "${MATRIX_CHART}" | sed 's/\//-/g') >> $GITHUB_OUTPUT
        env:
          MATRIX_CHART: ${{ matrix.chart }}
          MATRIX_REF_NAME: ${{ matrix.ref.name }}

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "shared-${{ matrix.ref.name }}-${{ steps.render.outputs.sanitized_name }}"
          path: "shared"

  diff_helm_charts:
    runs-on: ubuntu-latest
    needs:
      - get_changed_helm_charts
      - render_charts
    steps:
      - name: setup helm
        uses: azure/setup-helm@29960d0f5f19214b88e1d9ba750a9914ab0f1a2f #v4.0.0

      - name: download artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: shared-*
          merge-multiple: true
          path: "shared"

      - name: diff helm charts
        id: diff_helm_charts
        run: |
          for chart in ${CHARTS}; do
            chart_diff_output=$(diff -r "shared/base-charts/${chart}" "shared/head-charts/${chart}" || true)
            if [ -n "$chart_diff_output" ]; then
              echo -e "Changes found in chart: ${chart}\n$(diff -ruN shared/base-charts/${chart} shared/head-charts/${chart})\n" >> diff.log
            fi
          done
        env:
          CHARTS: ${{ needs.get_changed_helm_charts.outputs.charts }}
      - name: post diff as comment on pull request
        if: needs.get_changed_helm_charts.outputs.charts != ''
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const comment_char_limit = 65536; // GitHub comment character limit
            const diff_file = 'diff.log';

            if (fs.existsSync(diff_file)) {
              var diff = fs.readFileSync(diff_file, 'utf8');
            } else {
              console.log(diff_file + " not found")
              return
            }

            function splitComment(comment, maxSize, sepEnd, sepStart, comStart) {
              // Adapted from Atlantis SplitComment function
              // https://github.com/runatlantis/atlantis/blob/main/server/events/vcs/common/common.go#L18
              if (comment.length <= (comment_char_limit - comStart.length)) {
                return [comStart + diff]
              }
              maxWithSep = comment_char_limit - sepEnd.length - sepStart.length;
              var comments = [];
              var numComments = Math.ceil(comment.length / maxWithSep);
              for (var i = 0; i < numComments; i++) {
                var upTo = Math.min(comment.length, (i + 1) * maxWithSep);
                var portion = comment.slice(i * maxWithSep, upTo);
                if (i < numComments - 1) {
                  portion += sepEnd;
                }
                if (i > 0) {
                  portion = sepStart + portion
                } else {
                  portion = comStart + portion
                }
                comments.push(portion);
              }
              return comments;
            }

            var sepEnd = "\n```\n</details>" + "\n<br>\n\n**Warning**: Output length greater than max comment size. Continued in next comment.";
            var sepStart = "Continued from previous comment.\n<details><summary>Show Output</summary>\n\n" + "```diff\n";
            var comStart = "Changes found in Helm charts.\n<details><summary>Show Output</summary>\n\n" + "```diff\n";

            comments = splitComment(diff, comment_char_limit, sepEnd, sepStart, comStart);

            for (const comment of comments) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              })
            }
